const SELECT_JOYSTICK_BUTTON_TEXT = "JOYSTICK";
const SELECT_ACCELEROMETER_BUTTON_TEXT = "ACCELEROMETER";

const JOY_STICK_RANDOM_CONTROLLER = 1;
const JOY_STICK_COUNT_DOWN_CONTROLLER = 2;
const JOY_STICK_SINK_HOLE_CONTROLLER = 3;
const JOY_STICK_MULTI_GOAL_CONTROLLER = 4;

const CONTROLLER_LENGTH = 4;

const WIDGET_SIZE = 300.0;

const int ROWS = 15;
const int COLUMNS = 15;

const WALL_COUNT = 5;
const SINK_HOLE_COUNT = 5;

const GOAL_FLAG = -1;
const WALL_FLAG = -2;
const SINK_HOLE_FLAG = -3;
const OK_FLAG = -4;



